/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "images.unsplash.com" },
      { protocol: "https", hostname: "cdn.sanity.io" },
      { protocol: "https", hostname: "static.wixstatic.com" },
    ],
  },
  async redirects() {
    return [
      /* =====================================================================
       * Internal renames
       * =================================================================== */
      // /blog → /news (Blog menu renamed to News)
      { source: "/blog", destination: "/news", permanent: true },
      { source: "/blog/:slug*", destination: "/news/:slug*", permanent: true },

      /* =====================================================================
       * Wix → new site migration (301)
       *
       * Source URLs are taken directly from the live Wix sitemap. Each old URL
       * is mapped to the closest equivalent page on the new site, so existing
       * Google rankings + external backlinks land in the right place.
       *
       * If GSC shows 404s after cutover, add the URL here and redeploy.
       * =================================================================== */

      // Gallery — both old Wix galleries point to the unified /gallery page
      { source: "/2024-photo-gallery", destination: "/gallery", permanent: true },
      { source: "/2025-gallery", destination: "/gallery", permanent: true },

      // Sponsorship
      { source: "/2026-sponsorship", destination: "/sponsor", permanent: true },

      // Exhibitor / Exhibit
      { source: "/exhibitor-application", destination: "/exhibit-with-us#apply", permanent: true },
      { source: "/exhibitor-marketing-toolkit", destination: "/exhibit-with-us", permanent: true },
      // Wix exhibitor directory uses a "category" path
      { source: "/category/all-exhibitors", destination: "/exhibitors", permanent: true },
      { source: "/category/:slug*", destination: "/exhibitors", permanent: true },

      // Program / Demos / Competition
      { source: "/demo-times", destination: "/visit#whats-on", permanent: true },
      { source: "/explorer-competition", destination: "/news", permanent: true },

      // Generic inquiry/services landing → Visit page
      { source: "/inquiry-services-page", destination: "/visit", permanent: true },

      // Legal pages — slug name changes
      { source: "/privacy-policy", destination: "/privacy", permanent: true },
      { source: "/terms-conditions", destination: "/terms", permanent: true },
      { source: "/exhibitor-terms-conditions", destination: "/exhibitor-terms", permanent: true },

      /* =====================================================================
       * Individual exhibitor pages — Wix exposes each exhibitor at
       * /product-page/<slug>. 180+ of these exist (one per exhibitor) and
       * many have real Google rankings + external backlinks.
       *
       * We preserve every URL 1:1 by 301'ing /product-page/<slug> →
       * /exhibitors/<slug>. The slugs in exhibitors-2025.json match the
       * Wix slugs exactly, so the SEO equity flows straight through to the
       * matching detail page generated by app/exhibitors/[slug]/page.tsx.
       * =================================================================== */

      /* ---------------------------------------------------------------------
       * Overrides for old Wix slugs we DON'T have detail pages for.
       *
       * These exhibitors appeared in earlier years but aren't in our 2025
       * dataset, so /exhibitors/<slug> would 404. Surfaced by GSC's
       * "Not found (404)" report after the migration. Redirecting to the
       * /exhibitors directory keeps the link equity flowing instead of
       * letting it leak.
       *
       * Order matters: more-specific redirects MUST appear before the
       * generic /product-page/:slug* catch-all below — Next.js applies the
       * first match.
       * ------------------------------------------------------------------- */
      { source: "/product-page/happy-hire", destination: "/exhibitors", permanent: true },
      { source: "/product-page/kawasaki-motors-nz", destination: "/exhibitors", permanent: true },
      { source: "/product-page/coastguard-nz", destination: "/exhibitors", permanent: true },
      { source: "/product-page/west-coast-pie-co", destination: "/exhibitors", permanent: true },

      // Generic catch-all — matches every other /product-page/<slug> and
      // routes to the corresponding detail page. Any slug with no matching
      // exhibitor will 404 (which is the right answer once GSC tells us
      // about it — we can then add a specific override above).
      { source: "/product-page/:slug*", destination: "/exhibitors/:slug*", permanent: true },
      { source: "/product/:slug*", destination: "/exhibitors/:slug*", permanent: true },

      // Wix occasionally surfaces /exhibitor-page/<slug> as well (legacy
      // Stores layout). Same handling — route to the matching detail page.
      { source: "/exhibitor-page/:slug*", destination: "/exhibitors/:slug*", permanent: true },
      // Bare /exhibitor-page with no slug → directory
      { source: "/exhibitor-page", destination: "/exhibitors", permanent: true },
    ];
  },
};

module.exports = nextConfig;
